### ISSUE TITLE
Fonction pour supprimé le message du bot

### ISSUE THREAD

**Issue by Raph9213** [EntasiaOfficiel/Discord_Bot#1]
Salut,

Pour le bot, on pourrait faire que quand on envois un message et que le bot nous réponds, il ajoute un emoji ❌ sur le message du bot

Et si un membre du staff ou celui qui a fait la commande clic dessus, ça supprime le message + la commande.

wé

**Comment by iTrooz** [comment]
Fonction inutile (les staffs peuvent déjà le faire si il y a vraiment besoin de supprimer) : refusé
