### ISSUE TITLE
Code structure modifications

### ISSUE THREAD

**Issue by WeeskyBDW** [EntasiaOfficiel/Discord_Bot#3]
- ajouter le package.json

- bouger le dossier de config à la racine du bot

- mettre les 2 types de ficheirs de config: dev et prod

- renommer le dossier "entasia" en "Utils"

- Ajouter les entrées de https://github.com/WeeskyBDW/Discord_Bot/blob/master/.gitignore dans le gitignore

**Comment by iTrooz** [comment]
- le package json a été ajouté
- renommer/déplacer des fichiers n'a aucun impact
- la configuration de dev a été ajouté
- les entrées dans le .gitignore seront ajouté bientôt

**Comment by WeeskyBDW** [comment]
Pour le dossier entasia ce serait possible de faire quelque chose genre le renommer et trouver un moyen simple d'importer ? 

- c'est chiant de devoir moove entasia dans ndoe_modules et surtout si tu dois modif quelque chose ou si y'a eu un soucis avec l'installation de dépendances

- quand tu moove le dossier git croit que tu as delete le dossiers et donc si tu as le malheur de commit sans check, tu vas commit pour delete les fichiers du dossier entasia sur le github
